### ISSUE TITLE
Kaggle已禁SakuraLLM，請移除

### ISSUE THREAD

**Issue by cycham0** [Isotr0py/SakuraLLM-Notebooks#14]
Thank you for your inquiry. We have unblocked your "{id_name}" Kaggle account. The account was locked as there was SakuraLLM used in your account. Please avoid SakuraLLM on Kaggle platform as it is prohibited on Kaggle platform. This will lead to permanent ban. The account will not be reinstated if the account gets blocked again.

**Comment by Isotr0py** [comment]
Done.

**Comment by cycham0** [comment]
PS 暫時觀察來看，google colab用ngrok做api應該沒有問題

**Comment by Isotr0py** [comment]
还是先避一避风头吧，不然 colab 也 ban 了就麻了😢（SD-WebUI 并感）
