### ISSUE TITLE
[Kaggle] Kaggle update cuda version to 12.1.

### ISSUE THREAD

**Issue by sakura-umi** [Isotr0py/SakuraLLM-Notebooks#3]
目前不清楚是部分更新还是全部更新，已经有一部分人测试表明Kaggle将内置cuda版本升级到了12.1，所有软件包都需要更新到cu12x编译的版本，否则可能会出现找不到cudart 11动态链接库的报错。

**Comment by Isotr0py** [comment]
https://github.com/Kaggle/docker-python/pull/1352
已更新，似乎16号之后新建的notebook都是cuda12.1了
