### ISSUE TITLE
fetch失敗

### ISSUE THREAD

**Issue by junkpunk1122** [Isotr0py/SakuraLLM-Notebooks#4]
運行第一個cell時出錯:
![image](https://github.com/Isotr0py/SakuraLLM-Notebooks/assets/162812538/242cc750-bd02-4700-9fd0-e2f6c97df9fe)

Cloning into 'Sakura-13B-Galgame'...
remote: Enumerating objects: 848, done.
remote: Counting objects: 100% (306/306), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 848 (delta 225), reused 207 (delta 175), pack-reused 542
Receiving objects: 100% (848/848), 249.98 KiB | 8.06 MiB/s, done.
Resolving deltas: 100% (465/465), done.
/kaggle/working/Sakura-13B-Galgame/Sakura-13B-Galgame/Sakura-13B-Galgame
Collecting llama-cpp-python==0.2.39
  Downloading https://github.com/Isotr0py/SakuraLLM-Notebooks/releases/download/wheels/llama_cpp_python-0.2.39-cp310-cp310-manylinux_2_17_x86_64.whl (15.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 74.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: typing-extensions>=4.5.0 in /opt/conda/lib/python3.10/site-packages (from llama-cpp-python==0.2.39) (4.9.0)
Requirement already satisfied: numpy>=1.20.0 in /opt/conda/lib/python3.10/site-packages (from llama-cpp-python==0.2.39) (1.26.4)
Requirement already satisfied: diskcache>=5.6.1 in /opt/conda/lib/python3.10/site-packages (from llama-cpp-python==0.2.39) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in /opt/conda/lib/python3.10/site-packages (from llama-cpp-python==0.2.39) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2>=2.11.3->llama-cpp-python==0.2.39) (2.1.3)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/c-ares/libc-ares2_1.15.0-1ubuntu0.4_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nodejs/libnode64_10.19.0~dfsg-3ubuntu1.3_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nodejs/nodejs-doc_10.19.0~dfsg-3ubuntu1.3_all.deb  404  Not Found [IP: 91.189.91.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nodejs/nodejs_10.19.0~dfsg-3ubuntu1.3_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
/usr/bin/env: 'node': No such file or directory

**Comment by Isotr0py** [comment]
已修复，直接删掉这两行：
```bash
sudo apt-get install -qq -y nodejs
rm -f /opt/conda/bin/node
```
每次 kaggle 环境更新都能废掉不少代码（

**Comment by junkpunk1122** [comment]
成功了，感謝大佬😃
