### ISSUE TITLE
llama-cpp-python的wheels index page挂了

### ISSUE THREAD

**Issue by sakura-umi** [Isotr0py/SakuraLLM-Notebooks#7]
如题，我fork了一份自己构建了一个wheels index，可以将他的url改成`https://sakurallm.github.io/llama-cpp-python/whl/cu121`，不确定后续会不会出现同样的问题。

**Comment by Isotr0py** [comment]
已更换。

刚试了一下，现在 kaggle 的环境又能直接运行 `pip install llama-cpp-python` 构建 llama-cpp-python wheel 了，但说不准哪天 kaggle 更新镜像又把 CUDA 环境整挂了😑
